COMP: Provde C++11 compatible syntax
EMSegment/CommandLineApplication/EMSegmentAPIHelper.h:112:21: error:
invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]

  cout << "Setting "Slicer_HOME_ENVVAR_NAME" ..." << endl;


A space between concatenated string literals is required.